export const Deck = [
    '/imgs/Bomba.png',
    '/imgs/Cool.png',
    '/imgs/Daj kartu.png',
    '/imgs/Dno.png',
    '/imgs/Drugi smjer.png',
    '/imgs/Dupli samar.png',
    '/imgs/Macka 1.png',
    '/imgs/Macka 2.png',
    '/imgs/Macka 3.png',
    '/imgs/Macka 4.png',
    '/imgs/Macka 5.png',
    '/imgs/Napad.png',
    '/imgs/Nou.png',
    '/imgs/Pogledaj buducnost.png',
    '/imgs/Preskoci.png',
    '/imgs/Promijeni buducnost.png',
    '/imgs/Skopaj.png',
    '/imgs/Spas.png',
    '/imgs/Zmesaj.png',
]