export const DeckConfig = (numOfPlayers) => [
    {
        name: 'Bomba',
        img: '/imgs/Bomba.png',
        qty: numOfPlayers - 1,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Cool Mačka',
        img: '/imgs/Cool.png',
        qty: numOfPlayers < 4 ? 2 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Daj kartu',
        img: '/imgs/Daj kartu.png',
        qty: numOfPlayers < 4 ? 2 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Vuci s dna',
        img: '/imgs/Dno.png',
        qty: 2,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Drugi smjer',
        img: '/imgs/Drugi smjer.png',
        qty: numOfPlayers < 4 ? 2 : 3,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Dupli šamar',
        img: '/imgs/Dupli samar.png',
        qty: numOfPlayers < 4 ? 3 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Ivica',
        img: '/imgs/Macka 1.png',
        qty: numOfPlayers < 4 ? 3 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Kiki',
        img: '/imgs/Macka 2.png',
        qty: numOfPlayers < 4 ? 3 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Koki',
        img: '/imgs/Macka 3.png',
        qty: numOfPlayers < 4 ? 3 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Katica',
        img: '/imgs/Macka 4.png',
        qty: numOfPlayers < 4 ? 3 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Didi',
        img: '/imgs/Macka 5.png',
        qty: numOfPlayers < 4 ? 3 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Napad',
        img: '/imgs/Napad.png',
        qty: numOfPlayers < 4 ? 4 : 7,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Nou',
        img: '/imgs/Nou.png',
        qty: numOfPlayers < 4 ? 4 : 6,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Pogledaj budućnost',
        img: '/imgs/Pogledaj buducnost.png',
        qty: 3,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Preskoči',
        img: '/imgs/Preskoci.png',
        qty: numOfPlayers < 4 ? 4 : 7,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Promijeni budućnost',
        img: '/imgs/Promijeni buducnost.png',
        qty: numOfPlayers < 4 ? 2 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Skopaj',
        img: '/imgs/Skopaj.png',
        qty: 2,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Superhero',
        img: '/imgs/Spas.png',
        qty: numOfPlayers < 4 ? 3 : 7,
        imgBck: '/imgs/MackaPozadina.png',
    },
    {
        name: 'Zmešaj',
        img: '/imgs/Zmesaj.png',
        qty: numOfPlayers < 4 ? 2 : 4,
        imgBck: '/imgs/MackaPozadina.png',
    },
]